package mapping

// WorldCapitals is a map of capitals by continent.
var WorldCapitals = []Mapping{
	{
		Name:             "abuja",
		Code:             "ng",
		SVGName:          "Abuja",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "accra",
		Code:             "gh",
		SVGName:          "Accra",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "addis ababa",
		Code:             "et",
		SVGName:          "Addis Ababa",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "algiers",
		Code:             "dz",
		SVGName:          "Algiers",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "antananarivo",
		Code:             "mg",
		SVGName:          "Antananarivo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "asmara",
		Code:             "er",
		SVGName:          "Asmara",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "bamako",
		Code:             "ml",
		SVGName:          "Bamako",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "bangui",
		Code:             "cf",
		SVGName:          "Bangui",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "banjul",
		Code:             "gm",
		SVGName:          "Banjul",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "bissau",
		Code:             "gw",
		SVGName:          "Bissau",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "brazzaville",
		Code:             "cg",
		SVGName:          "Brazzaville",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "cairo",
		Code:             "eg",
		SVGName:          "Cairo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "cape town",
		Code:             "za",
		SVGName:          "Cape Town",
		AlternativeNames: []string{"pretoria", "bloemfontein"},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "conakry",
		Code:             "gn",
		SVGName:          "Conakry",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "dakar",
		Code:             "sn",
		SVGName:          "Dakar",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "djibouti",
		Code:             "dj",
		SVGName:          "Djibouti",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "dodoma",
		Code:             "tz",
		SVGName:          "Dodoma",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "freetown",
		Code:             "sl",
		SVGName:          "Freetown",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "gaborone",
		Code:             "bw",
		SVGName:          "Gaborone",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "gitega",
		Code:             "bi",
		SVGName:          "Gitega",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "harare",
		Code:             "zw",
		SVGName:          "Harare",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "juba",
		Code:             "ss",
		SVGName:          "Juba",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "kampala",
		Code:             "ug",
		SVGName:          "Kampala",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "khartoum",
		Code:             "sd",
		SVGName:          "Khartoum",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "kigali",
		Code:             "rw",
		SVGName:          "Kigali",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "kinshasa",
		Code:             "cd",
		SVGName:          "Kinshasa",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "libreville",
		Code:             "ga",
		SVGName:          "Libreville",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "lilongwe",
		Code:             "mw",
		SVGName:          "Lilongwe",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "lome",
		Code:             "tg",
		SVGName:          "Lome",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "luanda",
		Code:             "ao",
		SVGName:          "Luanda",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "lusaka",
		Code:             "zm",
		SVGName:          "Lusaka",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "malabo",
		Code:             "gq",
		SVGName:          "Malabo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "maputo",
		Code:             "mz",
		SVGName:          "Maputo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "maseru",
		Code:             "ls",
		SVGName:          "Maseru",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "mbabane",
		Code:             "sz",
		SVGName:          "Mbabane",
		AlternativeNames: []string{"lobamba"},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "mogadishu",
		Code:             "so",
		SVGName:          "Mogadishu",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "monrovia",
		Code:             "lr",
		SVGName:          "Monrovia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "moroni",
		Code:             "km",
		SVGName:          "Moroni",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "n'djamena",
		Code:             "td",
		SVGName:          "N'Djamena",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "nairobi",
		Code:             "ke",
		SVGName:          "Nairobi",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "niamey",
		Code:             "ne",
		SVGName:          "Niamey",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "nouakchott",
		Code:             "mr",
		SVGName:          "Nouakchott",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "ouagadougou",
		Code:             "bf",
		SVGName:          "Ouagadougou",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "port louis",
		Code:             "mu",
		SVGName:          "Port Louis",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "porto-novo",
		Code:             "bj",
		SVGName:          "Porto-Novo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "praia",
		Code:             "cv",
		SVGName:          "Praia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "rabat",
		Code:             "ma",
		SVGName:          "Rabat",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "sao tome",
		Code:             "st",
		SVGName:          "Sao Tome",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "tripoli",
		Code:             "ly",
		SVGName:          "Tripoli",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "tunis",
		Code:             "tn",
		SVGName:          "Tunis",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "victoria",
		Code:             "sc",
		SVGName:          "Victoria",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "windhoek",
		Code:             "na",
		SVGName:          "Windhoek",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "yamoussoukro",
		Code:             "ci",
		SVGName:          "Yamoussoukro",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "yaounde",
		Code:             "cm",
		SVGName:          "Yaounde",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "abu dhabi",
		Code:             "ae",
		SVGName:          "Abu Dhabi",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "amman",
		Code:             "jo",
		SVGName:          "Amman",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "ankara",
		Code:             "tr",
		SVGName:          "Ankara",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "ashgabat",
		Code:             "tm",
		SVGName:          "Ashgabat",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "baghdad",
		Code:             "iq",
		SVGName:          "Baghdad",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "baku",
		Code:             "az",
		SVGName:          "Baku",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "bandar seri begawan",
		Code:             "bn",
		SVGName:          "Bandar Seri Begawan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "bangkok",
		Code:             "th",
		SVGName:          "Bangkok",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "beijing",
		Code:             "cn",
		SVGName:          "Beijing",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "beirut",
		Code:             "lb",
		SVGName:          "Beirut",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "bishkek",
		Code:             "kg",
		SVGName:          "Bishkek",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "colombo",
		Code:             "lk",
		SVGName:          "Colombo",
		AlternativeNames: []string{"sri jayawardenepura kotte"},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "damascus",
		Code:             "sy",
		SVGName:          "Damascus",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "dhaka",
		Code:             "bd",
		SVGName:          "Dhaka",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "dili",
		Code:             "tl",
		SVGName:          "Dili",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "doha",
		Code:             "qa",
		SVGName:          "Doha",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "dushanbe",
		Code:             "tj",
		SVGName:          "Dushanbe",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "hanoi",
		Code:             "vn",
		SVGName:          "Hanoi",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "islamabad",
		Code:             "pk",
		SVGName:          "Islamabad",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "jakarta",
		Code:             "id",
		SVGName:          "Jakarta",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "jerusalem",
		Code:             "il",
		SVGName:          "Jerusalem",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "kabul",
		Code:             "af",
		SVGName:          "Kabul",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "kathmandu",
		Code:             "np",
		SVGName:          "Kathmandu",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "kuala lumpur",
		Code:             "my",
		SVGName:          "Kuala Lumpur",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "kuwait city",
		Code:             "kw",
		SVGName:          "Kuwait City",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "male",
		Code:             "mv",
		SVGName:          "Malé",
		AlternativeNames: []string{"malé"},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "manama",
		Code:             "bh",
		SVGName:          "Manama",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "manila",
		Code:             "ph",
		SVGName:          "Manila",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "moscow",
		Code:             "ru",
		SVGName:          "Moscow",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "muscat",
		Code:             "om",
		SVGName:          "Muscat",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "naypyitaw",
		Code:             "mm",
		SVGName:          "Naypyitaw",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "new delhi",
		Code:             "in",
		SVGName:          "New Delhi",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "nur-sultan",
		Code:             "kz",
		SVGName:          "Nur-Sultan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "phnom penh",
		Code:             "kh",
		SVGName:          "Phnom Penh",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "pyongyang",
		Code:             "kp",
		SVGName:          "Pyongyang",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "ramallah",
		Code:             "ps",
		SVGName:          "Ramallah",
		AlternativeNames: []string{"east jerusalem"},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "riyadh",
		Code:             "sa",
		SVGName:          "Riyadh",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "sana'a",
		Code:             "ye",
		SVGName:          "Sana'a",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "seoul",
		Code:             "kr",
		SVGName:          "Seoul",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "singapore",
		Code:             "sg",
		SVGName:          "Singapore",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "taipei",
		Code:             "tw",
		SVGName:          "Taipei",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "tashkent",
		Code:             "uz",
		SVGName:          "Tashkent",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "tbilisi",
		Code:             "ge",
		SVGName:          "Tbilisi",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "tehran",
		Code:             "ir",
		SVGName:          "Tehran",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "thimphu",
		Code:             "bt",
		SVGName:          "Thimphu",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "tokyo",
		Code:             "jp",
		SVGName:          "Tokyo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "ulaanbaatar",
		Code:             "mn",
		SVGName:          "Ulaanbaatar",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "vientiane",
		Code:             "la",
		SVGName:          "Vientiane",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "yerevan",
		Code:             "am",
		SVGName:          "Yerevan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "amsterdam",
		Code:             "nl",
		SVGName:          "Amsterdam",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "andorra la vella",
		Code:             "ad",
		SVGName:          "Andorra la Vella",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "athens",
		Code:             "gr",
		SVGName:          "Athens",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "belgrade",
		Code:             "rs",
		SVGName:          "Belgrade",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "berlin",
		Code:             "de",
		SVGName:          "Berlin",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "bern",
		Code:             "ch",
		SVGName:          "Bern",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "bratislava",
		Code:             "sk",
		SVGName:          "Bratislava",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "brussels",
		Code:             "be",
		SVGName:          "Brussels",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "bucharest",
		Code:             "ro",
		SVGName:          "Bucharest",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "budapest",
		Code:             "hu",
		SVGName:          "Budapest",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "chisinau",
		Code:             "md",
		SVGName:          "Chișinău",
		AlternativeNames: []string{"chișinău"},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "copenhagen",
		Code:             "dk",
		SVGName:          "Copenhagen",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "dublin",
		Code:             "ie",
		SVGName:          "Dublin",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "helsinki",
		Code:             "fi",
		SVGName:          "Helsinki",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "kyiv",
		Code:             "ua",
		SVGName:          "Kyiv",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "lisbon",
		Code:             "pt",
		SVGName:          "Lisbon",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "ljubljana",
		Code:             "si",
		SVGName:          "Ljubljana",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "london",
		Code:             "gb",
		SVGName:          "London",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "luxembourg city",
		Code:             "lu",
		SVGName:          "Luxembourg City",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "madrid",
		Code:             "es",
		SVGName:          "Madrid",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "minsk",
		Code:             "by",
		SVGName:          "Minsk",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "monaco",
		Code:             "mc",
		SVGName:          "Monaco",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "nicosia",
		Code:             "cy",
		SVGName:          "Nicosia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "oslo",
		Code:             "no",
		SVGName:          "Oslo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "paris",
		Code:             "fr",
		SVGName:          "Paris",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "podgorica",
		Code:             "me",
		SVGName:          "Podgorica",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "prague",
		Code:             "cz",
		SVGName:          "Prague",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "pristina",
		Code:             "xk",
		SVGName:          "Pristina",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "reykjavik",
		Code:             "is",
		SVGName:          "Reykjavík",
		AlternativeNames: []string{"reykjavík"},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "riga",
		Code:             "lv",
		SVGName:          "Riga",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "rome",
		Code:             "it",
		SVGName:          "Rome",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "san marino",
		Code:             "sm",
		SVGName:          "San Marino",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "sarajevo",
		Code:             "ba",
		SVGName:          "Sarajevo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "skopje",
		Code:             "mk",
		SVGName:          "Skopje",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "sofia",
		Code:             "bg",
		SVGName:          "Sofia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "stockholm",
		Code:             "se",
		SVGName:          "Stockholm",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "tallinn",
		Code:             "ee",
		SVGName:          "Tallinn",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "tirana",
		Code:             "al",
		SVGName:          "Tirana",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "vaduz",
		Code:             "li",
		SVGName:          "Vaduz",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "valletta",
		Code:             "mt",
		SVGName:          "Valletta",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "vatican city",
		Code:             "va",
		SVGName:          "Vatican City",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "vienna",
		Code:             "at",
		SVGName:          "Vienna",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "vilnius",
		Code:             "lt",
		SVGName:          "Vilnius",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "warsaw",
		Code:             "pl",
		SVGName:          "Warsaw",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "zagreb",
		Code:             "hr",
		SVGName:          "Zagreb",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "basseterre",
		Code:             "kn",
		SVGName:          "Basseterre",
		AlternativeNames: []string{"charlestown"},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "belmopan",
		Code:             "bz",
		SVGName:          "Belmopan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "bridgetown",
		Code:             "bb",
		SVGName:          "Bridgetown",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "castries",
		Code:             "lc",
		SVGName:          "Castries",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "guatemala city",
		Code:             "gt",
		SVGName:          "Guatemala City",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "havana",
		Code:             "cu",
		SVGName:          "Havana",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "kingston",
		Code:             "jm",
		SVGName:          "Kingston",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "kingstown",
		Code:             "vc",
		SVGName:          "Kingstown",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "managua",
		Code:             "ni",
		SVGName:          "Managua",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "mexico city",
		Code:             "mx",
		SVGName:          "Mexico City",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "nassau",
		Code:             "bs",
		SVGName:          "Nassau",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "ottawa",
		Code:             "ca",
		SVGName:          "Ottawa",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "panama city",
		Code:             "pa",
		SVGName:          "Panama City",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "port of spain",
		Code:             "tt",
		SVGName:          "Port of Spain",
		AlternativeNames: []string{"port-of-spain"},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "port-au-prince",
		Code:             "ht",
		SVGName:          "Port-au-Prince",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "roseau",
		Code:             "dm",
		SVGName:          "Roseau",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "saint george's",
		Code:             "gd",
		SVGName:          "Saint George's",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "saint john's",
		Code:             "ag",
		SVGName:          "Saint John's",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "san jose",
		Code:             "cr",
		SVGName:          "San José",
		AlternativeNames: []string{"san josé"},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "san salvador",
		Code:             "sv",
		SVGName:          "San Salvador",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "santo domingo",
		Code:             "do",
		SVGName:          "Santo Domingo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "tegucigalpa",
		Code:             "hn",
		SVGName:          "Tegucigalpa",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "washington, d.c.",
		Code:             "us",
		SVGName:          "Washington, D.C.",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "asuncion",
		Code:             "py",
		SVGName:          "Asunción",
		AlternativeNames: []string{"asunción"},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "bogota",
		Code:             "co",
		SVGName:          "Bogota",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "brasilia",
		Code:             "br",
		SVGName:          "Brasilia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "buenos aires",
		Code:             "ar",
		SVGName:          "Buenos Aires",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "caracas",
		Code:             "ve",
		SVGName:          "Caracas",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "georgetown",
		Code:             "gy",
		SVGName:          "Georgetown",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "la paz",
		Code:             "bo",
		SVGName:          "La Paz",
		AlternativeNames: []string{"sucre"},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "lima",
		Code:             "pe",
		SVGName:          "Lima",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "montevideo",
		Code:             "uy",
		SVGName:          "Montevideo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "paramaribo",
		Code:             "sr",
		SVGName:          "Paramaribo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "quito",
		Code:             "ec",
		SVGName:          "Quito",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "santiago",
		Code:             "cl",
		SVGName:          "Santiago",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "apia",
		Code:             "ws",
		SVGName:          "Apia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "canberra",
		Code:             "au",
		SVGName:          "Canberra",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "funafuti",
		Code:             "tv",
		SVGName:          "Funafuti",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "honiara",
		Code:             "sb",
		SVGName:          "Honiara",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "majuro",
		Code:             "mh",
		SVGName:          "Majuro",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "ngerulmud",
		Code:             "pw",
		SVGName:          "Ngerulmud",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "nuku'alofa",
		Code:             "to",
		SVGName:          "Nuku'alofa",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "palikir",
		Code:             "fm",
		SVGName:          "Palikir",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "port moresby",
		Code:             "pg",
		SVGName:          "Port Moresby",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "port vila",
		Code:             "vu",
		SVGName:          "Port Vila",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "suva",
		Code:             "fj",
		SVGName:          "Suva",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "tarawa",
		Code:             "ki",
		SVGName:          "Tarawa",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "wellington",
		Code:             "nz",
		SVGName:          "Wellington",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "yaren",
		Code:             "nr",
		SVGName:          "Yaren",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
}
