package mapping

// WorldCountries is a map of countries by continent.
var WorldCountries = []Mapping{
	{
		Name:             "algeria",
		Code:             "dz",
		SVGName:          "Algeria",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "angola",
		Code:             "ao",
		SVGName:          "Angola",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "benin",
		Code:             "bj",
		SVGName:          "Benin",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "botswana",
		Code:             "bw",
		SVGName:          "Botswana",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "burkina faso",
		Code:             "bf",
		SVGName:          "Burkina Faso",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "burundi",
		Code:             "bi",
		SVGName:          "Burundi",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "cameroon",
		Code:             "cm",
		SVGName:          "Cameroon",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "cape verde",
		Code:             "cv",
		SVGName:          "Cape Verde",
		AlternativeNames: []string{"cabo verde"},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "central african republic",
		Code:             "cf",
		SVGName:          "Central African Republic",
		AlternativeNames: []string{"car"},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "chad",
		Code:             "td",
		SVGName:          "Chad",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "comoros",
		Code:             "km",
		SVGName:          "Comoros",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "cote d'ivoire",
		Code:             "ci",
		SVGName:          "Côte d'Ivoire",
		AlternativeNames: []string{"côte d'ivoire", "ivory coast"},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "democratic republic of congo",
		Code:             "cd",
		SVGName:          "Democratic Republic of Congo",
		AlternativeNames: []string{"congo, democratic republic of the", "drc"},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "djibouti",
		Code:             "dj",
		SVGName:          "Djibouti",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "egypt",
		Code:             "eg",
		SVGName:          "Egypt",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "equatorial guinea",
		Code:             "gq",
		SVGName:          "Equatorial Guinea",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "eritrea",
		Code:             "er",
		SVGName:          "Eritrea",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "ethiopia",
		Code:             "et",
		SVGName:          "Ethiopia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "gabon",
		Code:             "ga",
		SVGName:          "Gabon",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "gambia",
		Code:             "gm",
		SVGName:          "Gambia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "ghana",
		Code:             "gh",
		SVGName:          "Ghana",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "guinea",
		Code:             "gn",
		SVGName:          "Guinea",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "guinea-bissau",
		Code:             "gw",
		SVGName:          "Guinea-Bissau",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "kenya",
		Code:             "ke",
		SVGName:          "Kenya",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "lesotho",
		Code:             "ls",
		SVGName:          "Lesotho",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "liberia",
		Code:             "lr",
		SVGName:          "Liberia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "libya",
		Code:             "ly",
		SVGName:          "Libya",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "madagascar",
		Code:             "mg",
		SVGName:          "Madagascar",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "malawi",
		Code:             "mw",
		SVGName:          "Malawi",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "mali",
		Code:             "ml",
		SVGName:          "Mali",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "mauritania",
		Code:             "mr",
		SVGName:          "Mauritania",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "mauritius",
		Code:             "mu",
		SVGName:          "Mauritius",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "morocco",
		Code:             "ma",
		SVGName:          "Morocco",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "mozambique",
		Code:             "mz",
		SVGName:          "Mozambique",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "namibia",
		Code:             "na",
		SVGName:          "Namibia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "niger",
		Code:             "ne",
		SVGName:          "Niger",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "nigeria",
		Code:             "ng",
		SVGName:          "Nigeria",
		AlternativeNames: []string{},
		Prefixes:         []string{"niger"},
		Group:            "africa",
	},
	{
		Name:             "republic of congo",
		Code:             "cg",
		SVGName:          "Republic of Congo",
		AlternativeNames: []string{"republic of the congo", "congo, republic of the"},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "rwanda",
		Code:             "rw",
		SVGName:          "Rwanda",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "sao tome and principe",
		Code:             "st",
		SVGName:          "Sao Tome and Principe",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "senegal",
		Code:             "sn",
		SVGName:          "Senegal",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "seychelles",
		Code:             "sc",
		SVGName:          "Seychelles",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "sierra leone",
		Code:             "sl",
		SVGName:          "Sierra Leone",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "somalia",
		Code:             "so",
		SVGName:          "Somalia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "south africa",
		Code:             "za",
		SVGName:          "South Africa",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "south sudan",
		Code:             "ss",
		SVGName:          "South Sudan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "sudan",
		Code:             "sd",
		SVGName:          "Sudan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "swaziland",
		Code:             "sz",
		SVGName:          "Swaziland",
		AlternativeNames: []string{"eswatini"},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "tanzania",
		Code:             "tz",
		SVGName:          "Tanzania",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "togo",
		Code:             "tg",
		SVGName:          "Togo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "tunisia",
		Code:             "tn",
		SVGName:          "Tunisia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "uganda",
		Code:             "ug",
		SVGName:          "Uganda",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "zambia",
		Code:             "zm",
		SVGName:          "Zambia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "zimbabwe",
		Code:             "zw",
		SVGName:          "Zimbabwe",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "africa",
	},
	{
		Name:             "afghanistan",
		Code:             "af",
		SVGName:          "Afghanistan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "armenia",
		Code:             "am",
		SVGName:          "Armenia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "azerbaijan",
		Code:             "az",
		SVGName:          "Azerbaijan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "bahrain",
		Code:             "bh",
		SVGName:          "Bahrain",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "bangladesh",
		Code:             "bd",
		SVGName:          "Bangladesh",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "bhutan",
		Code:             "bt",
		SVGName:          "Bhutan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "brunei",
		Code:             "bn",
		SVGName:          "Brunei Darussalam",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "cambodia",
		Code:             "kh",
		SVGName:          "Cambodia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "china",
		Code:             "cn",
		SVGName:          "China",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "georgia",
		Code:             "ge",
		SVGName:          "Georgia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "india",
		Code:             "in",
		SVGName:          "India",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "indonesia",
		Code:             "id",
		SVGName:          "Indonesia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "iran",
		Code:             "ir",
		SVGName:          "Iran",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "iraq",
		Code:             "iq",
		SVGName:          "Iraq",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "israel",
		Code:             "il",
		SVGName:          "Israel",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "japan",
		Code:             "jp",
		SVGName:          "Japan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "jordan",
		Code:             "jo",
		SVGName:          "Jordan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "kazakhstan",
		Code:             "kz",
		SVGName:          "Kazakhstan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "kuwait",
		Code:             "kw",
		SVGName:          "Kuwait",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "kyrgyzstan",
		Code:             "kg",
		SVGName:          "Kyrgyzstan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "lao people's democratic republic",
		Code:             "la",
		SVGName:          "Lao People's Democratic Republic",
		AlternativeNames: []string{"laos"},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "lebanon",
		Code:             "lb",
		SVGName:          "Lebanon",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "malaysia",
		Code:             "my",
		SVGName:          "Malaysia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "maldives",
		Code:             "mv",
		SVGName:          "Maldives",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "mongolia",
		Code:             "mn",
		SVGName:          "Mongolia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "myanmar",
		Code:             "mm",
		SVGName:          "Myanmar",
		AlternativeNames: []string{"burma"},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "nepal",
		Code:             "np",
		SVGName:          "Nepal",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "north korea",
		Code:             "kp",
		SVGName:          "North Korea",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "oman",
		Code:             "om",
		SVGName:          "Oman",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "pakistan",
		Code:             "pk",
		SVGName:          "Pakistan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "palestinian territories",
		Code:             "ps",
		SVGName:          "Palestinian Territories",
		AlternativeNames: []string{"palestine"},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "philippines",
		Code:             "ph",
		SVGName:          "Philippines",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "qatar",
		Code:             "qa",
		SVGName:          "Qatar",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "russia",
		Code:             "ru",
		SVGName:          "Russia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "saudi arabia",
		Code:             "sa",
		SVGName:          "Saudi Arabia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "singapore",
		Code:             "sg",
		SVGName:          "Singapore",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "south korea",
		Code:             "kr",
		SVGName:          "South Korea",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "sri lanka",
		Code:             "lk",
		SVGName:          "Sri Lanka",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "syria",
		Code:             "sy",
		SVGName:          "Syria",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "taiwan",
		Code:             "tw",
		SVGName:          "Taiwan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "tajikistan",
		Code:             "tj",
		SVGName:          "Tajikistan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "thailand",
		Code:             "th",
		SVGName:          "Thailand",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "timor-leste",
		Code:             "tl",
		SVGName:          "Timor-Leste",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "turkey",
		Code:             "tr",
		SVGName:          "Turkey",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "turkmenistan",
		Code:             "tm",
		SVGName:          "Turkmenistan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "united arab emirates",
		Code:             "ae",
		SVGName:          "United Arab Emirates",
		AlternativeNames: []string{"uae"},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "uzbekistan",
		Code:             "uz",
		SVGName:          "Uzbekistan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "vietnam",
		Code:             "vn",
		SVGName:          "Vietnam",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "yemen",
		Code:             "ye",
		SVGName:          "Yemen",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "asia",
	},
	{
		Name:             "albania",
		Code:             "al",
		SVGName:          "Albania",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "andorra",
		Code:             "ad",
		SVGName:          "Andorra",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "austria",
		Code:             "at",
		SVGName:          "Austria",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "belarus",
		Code:             "by",
		SVGName:          "Belarus",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "belgium",
		Code:             "be",
		SVGName:          "Belgium",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "bosnia and herzegovina",
		Code:             "ba",
		SVGName:          "Bosnia and Herzegovina",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "bulgaria",
		Code:             "bg",
		SVGName:          "Bulgaria",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "croatia",
		Code:             "hr",
		SVGName:          "Croatia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "cyprus",
		Code:             "cy",
		SVGName:          "Cyprus",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "czech republic",
		Code:             "cz",
		SVGName:          "Czech Republic",
		AlternativeNames: []string{"czechia"},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "denmark",
		Code:             "dk",
		SVGName:          "Denmark",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "estonia",
		Code:             "ee",
		SVGName:          "Estonia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "finland",
		Code:             "fi",
		SVGName:          "Finland",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "france",
		Code:             "fr",
		SVGName:          "France",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "germany",
		Code:             "de",
		SVGName:          "Germany",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "greece",
		Code:             "gr",
		SVGName:          "Greece",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "hungary",
		Code:             "hu",
		SVGName:          "Hungary",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "iceland",
		Code:             "is",
		SVGName:          "Iceland",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "ireland",
		Code:             "ie",
		SVGName:          "Ireland",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "italy",
		Code:             "it",
		SVGName:          "Italy",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "kosovo",
		Code:             "xk",
		SVGName:          "Kosovo",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "latvia",
		Code:             "lv",
		SVGName:          "Latvia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "liechtenstein",
		Code:             "li",
		SVGName:          "Liechtenstein",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "lithuania",
		Code:             "lt",
		SVGName:          "Lithuania",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "luxembourg",
		Code:             "lu",
		SVGName:          "Luxembourg",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "macedonia",
		Code:             "mk",
		SVGName:          "Macedonia",
		AlternativeNames: []string{"north macedonia"},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "malta",
		Code:             "mt",
		SVGName:          "Malta",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "moldova",
		Code:             "md",
		SVGName:          "Moldova",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "monaco",
		Code:             "mc",
		SVGName:          "Monaco",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "montenegro",
		Code:             "me",
		SVGName:          "Montenegro",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "netherlands",
		Code:             "nl",
		SVGName:          "Netherlands",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "norway",
		Code:             "no",
		SVGName:          "Norway",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "poland",
		Code:             "pl",
		SVGName:          "Poland",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "portugal",
		Code:             "pt",
		SVGName:          "Portugal",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "romania",
		Code:             "ro",
		SVGName:          "Romania",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "san marino",
		Code:             "sm",
		SVGName:          "San Marino",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "serbia",
		Code:             "rs",
		SVGName:          "Serbia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "slovakia",
		Code:             "sk",
		SVGName:          "Slovakia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "slovenia",
		Code:             "si",
		SVGName:          "Slovenia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "spain",
		Code:             "es",
		SVGName:          "Spain",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "sweden",
		Code:             "se",
		SVGName:          "Sweden",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "switzerland",
		Code:             "ch",
		SVGName:          "Switzerland",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "ukraine",
		Code:             "ua",
		SVGName:          "Ukraine",
		AlternativeNames: []string{},
		Prefixes:         []string{"uk"},
		Group:            "europe",
	},
	{
		Name:             "united kingdom",
		Code:             "gb",
		SVGName:          "United Kingdom",
		AlternativeNames: []string{"uk"},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "vatican city",
		Code:             "va",
		SVGName:          "Vatican City",
		AlternativeNames: []string{"holy see"},
		Prefixes:         []string{},
		Group:            "europe",
	},
	{
		Name:             "antigua and barbuda",
		Code:             "ag",
		SVGName:          "Antigua and Barbuda",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "bahamas",
		Code:             "bs",
		SVGName:          "Bahamas",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "barbados",
		Code:             "bb",
		SVGName:          "Barbados",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "belize",
		Code:             "bz",
		SVGName:          "Belize",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "canada",
		Code:             "ca",
		SVGName:          "Canada",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "costa rica",
		Code:             "cr",
		SVGName:          "Costa Rica",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "cuba",
		Code:             "cu",
		SVGName:          "Cuba",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "dominica",
		Code:             "dm",
		SVGName:          "Dominica",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "dominican republic",
		Code:             "do",
		SVGName:          "Dominican Republic",
		AlternativeNames: []string{},
		Prefixes:         []string{"dominica"},
		Group:            "north america",
	},
	{
		Name:             "el salvador",
		Code:             "sv",
		SVGName:          "El Salvador",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "grenada",
		Code:             "gd",
		SVGName:          "Grenada",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "guatemala",
		Code:             "gt",
		SVGName:          "Guatemala",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "haiti",
		Code:             "ht",
		SVGName:          "Haiti",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "honduras",
		Code:             "hn",
		SVGName:          "Honduras",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "jamaica",
		Code:             "jm",
		SVGName:          "Jamaica",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "mexico",
		Code:             "mx",
		SVGName:          "Mexico",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "nicaragua",
		Code:             "ni",
		SVGName:          "Nicaragua",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "panama",
		Code:             "pa",
		SVGName:          "Panama",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "saint kitts and nevis",
		Code:             "kn",
		SVGName:          "Saint Kitts and Nevis",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "saint lucia",
		Code:             "lc",
		SVGName:          "Saint Lucia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "saint vincent and the grenadines",
		Code:             "vc",
		SVGName:          "Saint Vincent and the Grenadines",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "trinidad and tobago",
		Code:             "tt",
		SVGName:          "Trinidad and Tobago",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "united states",
		Code:             "us",
		SVGName:          "United States",
		AlternativeNames: []string{"usa"},
		Prefixes:         []string{},
		Group:            "north america",
	},
	{
		Name:             "argentina",
		Code:             "ar",
		SVGName:          "Argentina",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "bolivia",
		Code:             "bo",
		SVGName:          "Bolivia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "brazil",
		Code:             "br",
		SVGName:          "Brazil",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "chile",
		Code:             "cl",
		SVGName:          "Chile",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "colombia",
		Code:             "co",
		SVGName:          "Colombia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "ecuador",
		Code:             "ec",
		SVGName:          "Ecuador",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "guyana",
		Code:             "gy",
		SVGName:          "Guyana",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "paraguay",
		Code:             "py",
		SVGName:          "Paraguay",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "peru",
		Code:             "pe",
		SVGName:          "Peru",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "suriname",
		Code:             "sr",
		SVGName:          "Suriname",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "uruguay",
		Code:             "uy",
		SVGName:          "Uruguay",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "venezuela",
		Code:             "ve",
		SVGName:          "Venezuela",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "south america",
	},
	{
		Name:             "australia",
		Code:             "au",
		SVGName:          "Australia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "federated states of micronesia",
		Code:             "fm",
		SVGName:          "Federated States of Micronesia",
		AlternativeNames: []string{"micronesia"},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "fiji",
		Code:             "fj",
		SVGName:          "Fiji",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "kiribati",
		Code:             "ki",
		SVGName:          "Kiribati",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "marshall islands",
		Code:             "mh",
		SVGName:          "Marshall Islands",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "nauru",
		Code:             "nr",
		SVGName:          "Nauru",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "new zealand",
		Code:             "nz",
		SVGName:          "New Zealand",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "palau",
		Code:             "pw",
		SVGName:          "Palau",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "papua new guinea",
		Code:             "pg",
		SVGName:          "Papua New Guinea",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "samoa",
		Code:             "ws",
		SVGName:          "Samoa",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "solomon islands",
		Code:             "sb",
		SVGName:          "Solomon Islands",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "tonga",
		Code:             "to",
		SVGName:          "Tonga",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "tuvalu",
		Code:             "tv",
		SVGName:          "Tuvalu",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
	{
		Name:             "vanuatu",
		Code:             "vu",
		SVGName:          "Vanuatu",
		AlternativeNames: []string{},
		Prefixes:         []string{},
		Group:            "oceania",
	},
}
