package mapping

var mappings = map[string][]Mapping{
	"capitals": {
		{
			Name:             "abuja",
			Code:             "ng",
			SVGName:          "Abuja",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "accra",
			Code:             "gh",
			SVGName:          "Accra",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "addis ababa",
			Code:             "et",
			SVGName:          "Addis Ababa",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "algiers",
			Code:             "dz",
			SVGName:          "Algiers",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "antananarivo",
			Code:             "mg",
			SVGName:          "Antananarivo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "asmara",
			Code:             "er",
			SVGName:          "Asmara",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "bamako",
			Code:             "ml",
			SVGName:          "Bamako",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "bangui",
			Code:             "cf",
			SVGName:          "Bangui",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "banjul",
			Code:             "gm",
			SVGName:          "Banjul",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "bissau",
			Code:             "gw",
			SVGName:          "Bissau",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "brazzaville",
			Code:             "cg",
			SVGName:          "Brazzaville",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "cairo",
			Code:             "eg",
			SVGName:          "Cairo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "cape town",
			Code:             "za",
			SVGName:          "Cape Town",
			AlternativeNames: []string{"pretoria", "bloemfontein"},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "conakry",
			Code:             "gn",
			SVGName:          "Conakry",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "dakar",
			Code:             "sn",
			SVGName:          "Dakar",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "djibouti",
			Code:             "dj",
			SVGName:          "Djibouti",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "dodoma",
			Code:             "tz",
			SVGName:          "Dodoma",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "freetown",
			Code:             "sl",
			SVGName:          "Freetown",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "gaborone",
			Code:             "bw",
			SVGName:          "Gaborone",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "gitega",
			Code:             "bi",
			SVGName:          "Gitega",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "harare",
			Code:             "zw",
			SVGName:          "Harare",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "juba",
			Code:             "ss",
			SVGName:          "Juba",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "kampala",
			Code:             "ug",
			SVGName:          "Kampala",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "khartoum",
			Code:             "sd",
			SVGName:          "Khartoum",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "kigali",
			Code:             "rw",
			SVGName:          "Kigali",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "kinshasa",
			Code:             "cd",
			SVGName:          "Kinshasa",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "libreville",
			Code:             "ga",
			SVGName:          "Libreville",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "lilongwe",
			Code:             "mw",
			SVGName:          "Lilongwe",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "lome",
			Code:             "tg",
			SVGName:          "Lome",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "luanda",
			Code:             "ao",
			SVGName:          "Luanda",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "lusaka",
			Code:             "zm",
			SVGName:          "Lusaka",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "malabo",
			Code:             "gq",
			SVGName:          "Malabo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "maputo",
			Code:             "mz",
			SVGName:          "Maputo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "maseru",
			Code:             "ls",
			SVGName:          "Maseru",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "mbabane",
			Code:             "sz",
			SVGName:          "Mbabane",
			AlternativeNames: []string{"lobamba"},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "mogadishu",
			Code:             "so",
			SVGName:          "Mogadishu",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "monrovia",
			Code:             "lr",
			SVGName:          "Monrovia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "moroni",
			Code:             "km",
			SVGName:          "Moroni",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "n'djamena",
			Code:             "td",
			SVGName:          "N'Djamena",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "nairobi",
			Code:             "ke",
			SVGName:          "Nairobi",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "niamey",
			Code:             "ne",
			SVGName:          "Niamey",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "nouakchott",
			Code:             "mr",
			SVGName:          "Nouakchott",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "ouagadougou",
			Code:             "bf",
			SVGName:          "Ouagadougou",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "port louis",
			Code:             "mu",
			SVGName:          "Port Louis",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "porto-novo",
			Code:             "bj",
			SVGName:          "Porto-Novo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "praia",
			Code:             "cv",
			SVGName:          "Praia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "rabat",
			Code:             "ma",
			SVGName:          "Rabat",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "sao tome",
			Code:             "st",
			SVGName:          "Sao Tome",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "tripoli",
			Code:             "ly",
			SVGName:          "Tripoli",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "tunis",
			Code:             "tn",
			SVGName:          "Tunis",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "victoria",
			Code:             "sc",
			SVGName:          "Victoria",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "windhoek",
			Code:             "na",
			SVGName:          "Windhoek",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "yamoussoukro",
			Code:             "ci",
			SVGName:          "Yamoussoukro",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "yaounde",
			Code:             "cm",
			SVGName:          "Yaounde",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "abu dhabi",
			Code:             "ae",
			SVGName:          "Abu Dhabi",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "amman",
			Code:             "jo",
			SVGName:          "Amman",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "ankara",
			Code:             "tr",
			SVGName:          "Ankara",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "ashgabat",
			Code:             "tm",
			SVGName:          "Ashgabat",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "baghdad",
			Code:             "iq",
			SVGName:          "Baghdad",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "baku",
			Code:             "az",
			SVGName:          "Baku",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "bandar seri begawan",
			Code:             "bn",
			SVGName:          "Bandar Seri Begawan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "bangkok",
			Code:             "th",
			SVGName:          "Bangkok",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "beijing",
			Code:             "cn",
			SVGName:          "Beijing",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "beirut",
			Code:             "lb",
			SVGName:          "Beirut",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "bishkek",
			Code:             "kg",
			SVGName:          "Bishkek",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "colombo",
			Code:             "lk",
			SVGName:          "Colombo",
			AlternativeNames: []string{"sri jayawardenepura kotte"},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "damascus",
			Code:             "sy",
			SVGName:          "Damascus",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "dhaka",
			Code:             "bd",
			SVGName:          "Dhaka",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "dili",
			Code:             "tl",
			SVGName:          "Dili",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "doha",
			Code:             "qa",
			SVGName:          "Doha",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "dushanbe",
			Code:             "tj",
			SVGName:          "Dushanbe",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "hanoi",
			Code:             "vn",
			SVGName:          "Hanoi",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "islamabad",
			Code:             "pk",
			SVGName:          "Islamabad",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "jakarta",
			Code:             "id",
			SVGName:          "Jakarta",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "jerusalem",
			Code:             "il",
			SVGName:          "Jerusalem",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "kabul",
			Code:             "af",
			SVGName:          "Kabul",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "kathmandu",
			Code:             "np",
			SVGName:          "Kathmandu",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "kuala lumpur",
			Code:             "my",
			SVGName:          "Kuala Lumpur",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "kuwait city",
			Code:             "kw",
			SVGName:          "Kuwait City",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "male",
			Code:             "mv",
			SVGName:          "Malé",
			AlternativeNames: []string{"malé"},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "manama",
			Code:             "bh",
			SVGName:          "Manama",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "manila",
			Code:             "ph",
			SVGName:          "Manila",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "moscow",
			Code:             "ru",
			SVGName:          "Moscow",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "muscat",
			Code:             "om",
			SVGName:          "Muscat",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "naypyitaw",
			Code:             "mm",
			SVGName:          "Naypyitaw",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "new delhi",
			Code:             "in",
			SVGName:          "New Delhi",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "nur-sultan",
			Code:             "kz",
			SVGName:          "Nur-Sultan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "phnom penh",
			Code:             "kh",
			SVGName:          "Phnom Penh",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "pyongyang",
			Code:             "kp",
			SVGName:          "Pyongyang",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "ramallah",
			Code:             "ps",
			SVGName:          "Ramallah",
			AlternativeNames: []string{"east jerusalem"},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "riyadh",
			Code:             "sa",
			SVGName:          "Riyadh",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "sana'a",
			Code:             "ye",
			SVGName:          "Sana'a",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "seoul",
			Code:             "kr",
			SVGName:          "Seoul",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "singapore",
			Code:             "sg",
			SVGName:          "Singapore",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "taipei",
			Code:             "tw",
			SVGName:          "Taipei",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "tashkent",
			Code:             "uz",
			SVGName:          "Tashkent",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "tbilisi",
			Code:             "ge",
			SVGName:          "Tbilisi",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "tehran",
			Code:             "ir",
			SVGName:          "Tehran",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "thimphu",
			Code:             "bt",
			SVGName:          "Thimphu",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "tokyo",
			Code:             "jp",
			SVGName:          "Tokyo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "ulaanbaatar",
			Code:             "mn",
			SVGName:          "Ulaanbaatar",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "vientiane",
			Code:             "la",
			SVGName:          "Vientiane",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "yerevan",
			Code:             "am",
			SVGName:          "Yerevan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "amsterdam",
			Code:             "nl",
			SVGName:          "Amsterdam",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "andorra la vella",
			Code:             "ad",
			SVGName:          "Andorra la Vella",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "athens",
			Code:             "gr",
			SVGName:          "Athens",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "belgrade",
			Code:             "rs",
			SVGName:          "Belgrade",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "berlin",
			Code:             "de",
			SVGName:          "Berlin",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "bern",
			Code:             "ch",
			SVGName:          "Bern",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "bratislava",
			Code:             "sk",
			SVGName:          "Bratislava",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "brussels",
			Code:             "be",
			SVGName:          "Brussels",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "bucharest",
			Code:             "ro",
			SVGName:          "Bucharest",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "budapest",
			Code:             "hu",
			SVGName:          "Budapest",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "chisinau",
			Code:             "md",
			SVGName:          "Chișinău",
			AlternativeNames: []string{"chișinău"},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "copenhagen",
			Code:             "dk",
			SVGName:          "Copenhagen",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "dublin",
			Code:             "ie",
			SVGName:          "Dublin",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "helsinki",
			Code:             "fi",
			SVGName:          "Helsinki",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "kyiv",
			Code:             "ua",
			SVGName:          "Kyiv",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "lisbon",
			Code:             "pt",
			SVGName:          "Lisbon",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "ljubljana",
			Code:             "si",
			SVGName:          "Ljubljana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "london",
			Code:             "gb",
			SVGName:          "London",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "luxembourg city",
			Code:             "lu",
			SVGName:          "Luxembourg City",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "madrid",
			Code:             "es",
			SVGName:          "Madrid",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "minsk",
			Code:             "by",
			SVGName:          "Minsk",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "monaco",
			Code:             "mc",
			SVGName:          "Monaco",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "nicosia",
			Code:             "cy",
			SVGName:          "Nicosia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "oslo",
			Code:             "no",
			SVGName:          "Oslo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "paris",
			Code:             "fr",
			SVGName:          "Paris",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "podgorica",
			Code:             "me",
			SVGName:          "Podgorica",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "prague",
			Code:             "cz",
			SVGName:          "Prague",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "pristina",
			Code:             "xk",
			SVGName:          "Pristina",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "reykjavik",
			Code:             "is",
			SVGName:          "Reykjavík",
			AlternativeNames: []string{"reykjavík"},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "riga",
			Code:             "lv",
			SVGName:          "Riga",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "rome",
			Code:             "it",
			SVGName:          "Rome",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "san marino",
			Code:             "sm",
			SVGName:          "San Marino",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "sarajevo",
			Code:             "ba",
			SVGName:          "Sarajevo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "skopje",
			Code:             "mk",
			SVGName:          "Skopje",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "sofia",
			Code:             "bg",
			SVGName:          "Sofia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "stockholm",
			Code:             "se",
			SVGName:          "Stockholm",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "tallinn",
			Code:             "ee",
			SVGName:          "Tallinn",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "tirana",
			Code:             "al",
			SVGName:          "Tirana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "vaduz",
			Code:             "li",
			SVGName:          "Vaduz",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "valletta",
			Code:             "mt",
			SVGName:          "Valletta",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "vatican city",
			Code:             "va",
			SVGName:          "Vatican City",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "vienna",
			Code:             "at",
			SVGName:          "Vienna",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "vilnius",
			Code:             "lt",
			SVGName:          "Vilnius",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "warsaw",
			Code:             "pl",
			SVGName:          "Warsaw",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "zagreb",
			Code:             "hr",
			SVGName:          "Zagreb",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "basseterre",
			Code:             "kn",
			SVGName:          "Basseterre",
			AlternativeNames: []string{"charlestown"},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "belmopan",
			Code:             "bz",
			SVGName:          "Belmopan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "bridgetown",
			Code:             "bb",
			SVGName:          "Bridgetown",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "castries",
			Code:             "lc",
			SVGName:          "Castries",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "guatemala city",
			Code:             "gt",
			SVGName:          "Guatemala City",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "havana",
			Code:             "cu",
			SVGName:          "Havana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "kingston",
			Code:             "jm",
			SVGName:          "Kingston",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "kingstown",
			Code:             "vc",
			SVGName:          "Kingstown",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "managua",
			Code:             "ni",
			SVGName:          "Managua",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "mexico city",
			Code:             "mx",
			SVGName:          "Mexico City",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "nassau",
			Code:             "bs",
			SVGName:          "Nassau",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "ottawa",
			Code:             "ca",
			SVGName:          "Ottawa",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "panama city",
			Code:             "pa",
			SVGName:          "Panama City",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "port of spain",
			Code:             "tt",
			SVGName:          "Port of Spain",
			AlternativeNames: []string{"port-of-spain"},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "port-au-prince",
			Code:             "ht",
			SVGName:          "Port-au-Prince",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "roseau",
			Code:             "dm",
			SVGName:          "Roseau",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "saint george's",
			Code:             "gd",
			SVGName:          "Saint George's",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "saint john's",
			Code:             "ag",
			SVGName:          "Saint John's",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "san jose",
			Code:             "cr",
			SVGName:          "San José",
			AlternativeNames: []string{"san josé"},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "san salvador",
			Code:             "sv",
			SVGName:          "San Salvador",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "santo domingo",
			Code:             "do",
			SVGName:          "Santo Domingo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "tegucigalpa",
			Code:             "hn",
			SVGName:          "Tegucigalpa",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "washington, d.c.",
			Code:             "us",
			SVGName:          "Washington, D.C.",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "asuncion",
			Code:             "py",
			SVGName:          "Asunción",
			AlternativeNames: []string{"asunción"},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "bogota",
			Code:             "co",
			SVGName:          "Bogota",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "brasilia",
			Code:             "br",
			SVGName:          "Brasilia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "buenos aires",
			Code:             "ar",
			SVGName:          "Buenos Aires",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "caracas",
			Code:             "ve",
			SVGName:          "Caracas",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "georgetown",
			Code:             "gy",
			SVGName:          "Georgetown",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "la paz",
			Code:             "bo",
			SVGName:          "La Paz",
			AlternativeNames: []string{"sucre"},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "lima",
			Code:             "pe",
			SVGName:          "Lima",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "montevideo",
			Code:             "uy",
			SVGName:          "Montevideo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "paramaribo",
			Code:             "sr",
			SVGName:          "Paramaribo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "quito",
			Code:             "ec",
			SVGName:          "Quito",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "santiago",
			Code:             "cl",
			SVGName:          "Santiago",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "apia",
			Code:             "ws",
			SVGName:          "Apia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "canberra",
			Code:             "au",
			SVGName:          "Canberra",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "funafuti",
			Code:             "tv",
			SVGName:          "Funafuti",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "honiara",
			Code:             "sb",
			SVGName:          "Honiara",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "majuro",
			Code:             "mh",
			SVGName:          "Majuro",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "ngerulmud",
			Code:             "pw",
			SVGName:          "Ngerulmud",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "nuku'alofa",
			Code:             "to",
			SVGName:          "Nuku'alofa",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "palikir",
			Code:             "fm",
			SVGName:          "Palikir",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "port moresby",
			Code:             "pg",
			SVGName:          "Port Moresby",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "port vila",
			Code:             "vu",
			SVGName:          "Port Vila",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "suva",
			Code:             "fj",
			SVGName:          "Suva",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "tarawa",
			Code:             "ki",
			SVGName:          "Tarawa",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "wellington",
			Code:             "nz",
			SVGName:          "Wellington",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "yaren",
			Code:             "nr",
			SVGName:          "Yaren",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
	},
	"countries": {
		{
			Name:             "algeria",
			Code:             "dz",
			SVGName:          "Algeria",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "angola",
			Code:             "ao",
			SVGName:          "Angola",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "benin",
			Code:             "bj",
			SVGName:          "Benin",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "botswana",
			Code:             "bw",
			SVGName:          "Botswana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "burkina faso",
			Code:             "bf",
			SVGName:          "Burkina Faso",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "burundi",
			Code:             "bi",
			SVGName:          "Burundi",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "cameroon",
			Code:             "cm",
			SVGName:          "Cameroon",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "cape verde",
			Code:             "cv",
			SVGName:          "Cape Verde",
			AlternativeNames: []string{"cabo verde"},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "central african republic",
			Code:             "cf",
			SVGName:          "Central African Republic",
			AlternativeNames: []string{"car"},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "chad",
			Code:             "td",
			SVGName:          "Chad",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "comoros",
			Code:             "km",
			SVGName:          "Comoros",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "cote d'ivoire",
			Code:             "ci",
			SVGName:          "Côte d'Ivoire",
			AlternativeNames: []string{"côte d'ivoire", "ivory coast"},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "democratic republic of congo",
			Code:             "cd",
			SVGName:          "Democratic Republic of Congo",
			AlternativeNames: []string{"congo, democratic republic of the", "drc"},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "djibouti",
			Code:             "dj",
			SVGName:          "Djibouti",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "egypt",
			Code:             "eg",
			SVGName:          "Egypt",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "equatorial guinea",
			Code:             "gq",
			SVGName:          "Equatorial Guinea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "eritrea",
			Code:             "er",
			SVGName:          "Eritrea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "ethiopia",
			Code:             "et",
			SVGName:          "Ethiopia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "gabon",
			Code:             "ga",
			SVGName:          "Gabon",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "gambia",
			Code:             "gm",
			SVGName:          "Gambia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "ghana",
			Code:             "gh",
			SVGName:          "Ghana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "guinea",
			Code:             "gn",
			SVGName:          "Guinea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "guinea-bissau",
			Code:             "gw",
			SVGName:          "Guinea-Bissau",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "kenya",
			Code:             "ke",
			SVGName:          "Kenya",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "lesotho",
			Code:             "ls",
			SVGName:          "Lesotho",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "liberia",
			Code:             "lr",
			SVGName:          "Liberia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "libya",
			Code:             "ly",
			SVGName:          "Libya",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "madagascar",
			Code:             "mg",
			SVGName:          "Madagascar",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "malawi",
			Code:             "mw",
			SVGName:          "Malawi",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "mali",
			Code:             "ml",
			SVGName:          "Mali",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "mauritania",
			Code:             "mr",
			SVGName:          "Mauritania",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "mauritius",
			Code:             "mu",
			SVGName:          "Mauritius",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "morocco",
			Code:             "ma",
			SVGName:          "Morocco",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "mozambique",
			Code:             "mz",
			SVGName:          "Mozambique",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "namibia",
			Code:             "na",
			SVGName:          "Namibia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "niger",
			Code:             "ne",
			SVGName:          "Niger",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "nigeria",
			Code:             "ng",
			SVGName:          "Nigeria",
			AlternativeNames: []string{},
			Prefixes:         []string{"niger"},
			Group:            "africa",
		},
		{
			Name:             "republic of congo",
			Code:             "cg",
			SVGName:          "Republic of Congo",
			AlternativeNames: []string{"republic of the congo", "congo, republic of the"},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "rwanda",
			Code:             "rw",
			SVGName:          "Rwanda",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "sao tome and principe",
			Code:             "st",
			SVGName:          "Sao Tome and Principe",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "senegal",
			Code:             "sn",
			SVGName:          "Senegal",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "seychelles",
			Code:             "sc",
			SVGName:          "Seychelles",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "sierra leone",
			Code:             "sl",
			SVGName:          "Sierra Leone",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "somalia",
			Code:             "so",
			SVGName:          "Somalia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "south africa",
			Code:             "za",
			SVGName:          "South Africa",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "south sudan",
			Code:             "ss",
			SVGName:          "South Sudan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "sudan",
			Code:             "sd",
			SVGName:          "Sudan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "swaziland",
			Code:             "sz",
			SVGName:          "Swaziland",
			AlternativeNames: []string{"eswatini"},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "tanzania",
			Code:             "tz",
			SVGName:          "Tanzania",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "togo",
			Code:             "tg",
			SVGName:          "Togo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "tunisia",
			Code:             "tn",
			SVGName:          "Tunisia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "uganda",
			Code:             "ug",
			SVGName:          "Uganda",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "zambia",
			Code:             "zm",
			SVGName:          "Zambia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "zimbabwe",
			Code:             "zw",
			SVGName:          "Zimbabwe",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "africa",
		},
		{
			Name:             "afghanistan",
			Code:             "af",
			SVGName:          "Afghanistan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "armenia",
			Code:             "am",
			SVGName:          "Armenia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "azerbaijan",
			Code:             "az",
			SVGName:          "Azerbaijan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "bahrain",
			Code:             "bh",
			SVGName:          "Bahrain",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "bangladesh",
			Code:             "bd",
			SVGName:          "Bangladesh",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "bhutan",
			Code:             "bt",
			SVGName:          "Bhutan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "brunei",
			Code:             "bn",
			SVGName:          "Brunei Darussalam",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "cambodia",
			Code:             "kh",
			SVGName:          "Cambodia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "china",
			Code:             "cn",
			SVGName:          "China",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "georgia",
			Code:             "ge",
			SVGName:          "Georgia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "india",
			Code:             "in",
			SVGName:          "India",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "indonesia",
			Code:             "id",
			SVGName:          "Indonesia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "iran",
			Code:             "ir",
			SVGName:          "Iran",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "iraq",
			Code:             "iq",
			SVGName:          "Iraq",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "israel",
			Code:             "il",
			SVGName:          "Israel",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "japan",
			Code:             "jp",
			SVGName:          "Japan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "jordan",
			Code:             "jo",
			SVGName:          "Jordan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "kazakhstan",
			Code:             "kz",
			SVGName:          "Kazakhstan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "kuwait",
			Code:             "kw",
			SVGName:          "Kuwait",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "kyrgyzstan",
			Code:             "kg",
			SVGName:          "Kyrgyzstan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "lao people's democratic republic",
			Code:             "la",
			SVGName:          "Lao People's Democratic Republic",
			AlternativeNames: []string{"laos"},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "lebanon",
			Code:             "lb",
			SVGName:          "Lebanon",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "malaysia",
			Code:             "my",
			SVGName:          "Malaysia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "maldives",
			Code:             "mv",
			SVGName:          "Maldives",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "mongolia",
			Code:             "mn",
			SVGName:          "Mongolia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "myanmar",
			Code:             "mm",
			SVGName:          "Myanmar",
			AlternativeNames: []string{"burma"},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "nepal",
			Code:             "np",
			SVGName:          "Nepal",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "north korea",
			Code:             "kp",
			SVGName:          "North Korea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "oman",
			Code:             "om",
			SVGName:          "Oman",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "pakistan",
			Code:             "pk",
			SVGName:          "Pakistan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "palestinian territories",
			Code:             "ps",
			SVGName:          "Palestinian Territories",
			AlternativeNames: []string{"palestine"},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "philippines",
			Code:             "ph",
			SVGName:          "Philippines",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "qatar",
			Code:             "qa",
			SVGName:          "Qatar",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "russia",
			Code:             "ru",
			SVGName:          "Russia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "saudi arabia",
			Code:             "sa",
			SVGName:          "Saudi Arabia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "singapore",
			Code:             "sg",
			SVGName:          "Singapore",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "south korea",
			Code:             "kr",
			SVGName:          "South Korea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "sri lanka",
			Code:             "lk",
			SVGName:          "Sri Lanka",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "syria",
			Code:             "sy",
			SVGName:          "Syria",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "taiwan",
			Code:             "tw",
			SVGName:          "Taiwan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "tajikistan",
			Code:             "tj",
			SVGName:          "Tajikistan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "thailand",
			Code:             "th",
			SVGName:          "Thailand",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "timor-leste",
			Code:             "tl",
			SVGName:          "Timor-Leste",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "turkey",
			Code:             "tr",
			SVGName:          "Turkey",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "turkmenistan",
			Code:             "tm",
			SVGName:          "Turkmenistan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "united arab emirates",
			Code:             "ae",
			SVGName:          "United Arab Emirates",
			AlternativeNames: []string{"uae"},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "uzbekistan",
			Code:             "uz",
			SVGName:          "Uzbekistan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "vietnam",
			Code:             "vn",
			SVGName:          "Vietnam",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "yemen",
			Code:             "ye",
			SVGName:          "Yemen",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "asia",
		},
		{
			Name:             "albania",
			Code:             "al",
			SVGName:          "Albania",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "andorra",
			Code:             "ad",
			SVGName:          "Andorra",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "austria",
			Code:             "at",
			SVGName:          "Austria",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "belarus",
			Code:             "by",
			SVGName:          "Belarus",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "belgium",
			Code:             "be",
			SVGName:          "Belgium",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "bosnia and herzegovina",
			Code:             "ba",
			SVGName:          "Bosnia and Herzegovina",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "bulgaria",
			Code:             "bg",
			SVGName:          "Bulgaria",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "croatia",
			Code:             "hr",
			SVGName:          "Croatia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "cyprus",
			Code:             "cy",
			SVGName:          "Cyprus",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "czech republic",
			Code:             "cz",
			SVGName:          "Czech Republic",
			AlternativeNames: []string{"czechia"},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "denmark",
			Code:             "dk",
			SVGName:          "Denmark",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "estonia",
			Code:             "ee",
			SVGName:          "Estonia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "finland",
			Code:             "fi",
			SVGName:          "Finland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "france",
			Code:             "fr",
			SVGName:          "France",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "germany",
			Code:             "de",
			SVGName:          "Germany",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "greece",
			Code:             "gr",
			SVGName:          "Greece",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "hungary",
			Code:             "hu",
			SVGName:          "Hungary",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "iceland",
			Code:             "is",
			SVGName:          "Iceland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "ireland",
			Code:             "ie",
			SVGName:          "Ireland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "italy",
			Code:             "it",
			SVGName:          "Italy",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "kosovo",
			Code:             "xk",
			SVGName:          "Kosovo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "latvia",
			Code:             "lv",
			SVGName:          "Latvia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "liechtenstein",
			Code:             "li",
			SVGName:          "Liechtenstein",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "lithuania",
			Code:             "lt",
			SVGName:          "Lithuania",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "luxembourg",
			Code:             "lu",
			SVGName:          "Luxembourg",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "macedonia",
			Code:             "mk",
			SVGName:          "Macedonia",
			AlternativeNames: []string{"north macedonia"},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "malta",
			Code:             "mt",
			SVGName:          "Malta",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "moldova",
			Code:             "md",
			SVGName:          "Moldova",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "monaco",
			Code:             "mc",
			SVGName:          "Monaco",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "montenegro",
			Code:             "me",
			SVGName:          "Montenegro",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "netherlands",
			Code:             "nl",
			SVGName:          "Netherlands",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "norway",
			Code:             "no",
			SVGName:          "Norway",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "poland",
			Code:             "pl",
			SVGName:          "Poland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "portugal",
			Code:             "pt",
			SVGName:          "Portugal",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "romania",
			Code:             "ro",
			SVGName:          "Romania",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "san marino",
			Code:             "sm",
			SVGName:          "San Marino",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "serbia",
			Code:             "rs",
			SVGName:          "Serbia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "slovakia",
			Code:             "sk",
			SVGName:          "Slovakia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "slovenia",
			Code:             "si",
			SVGName:          "Slovenia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "spain",
			Code:             "es",
			SVGName:          "Spain",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "sweden",
			Code:             "se",
			SVGName:          "Sweden",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "switzerland",
			Code:             "ch",
			SVGName:          "Switzerland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "ukraine",
			Code:             "ua",
			SVGName:          "Ukraine",
			AlternativeNames: []string{},
			Prefixes:         []string{"uk"},
			Group:            "europe",
		},
		{
			Name:             "united kingdom",
			Code:             "gb",
			SVGName:          "United Kingdom",
			AlternativeNames: []string{"uk"},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "vatican city",
			Code:             "va",
			SVGName:          "Vatican City",
			AlternativeNames: []string{"holy see"},
			Prefixes:         []string{},
			Group:            "europe",
		},
		{
			Name:             "antigua and barbuda",
			Code:             "ag",
			SVGName:          "Antigua and Barbuda",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "bahamas",
			Code:             "bs",
			SVGName:          "Bahamas",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "barbados",
			Code:             "bb",
			SVGName:          "Barbados",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "belize",
			Code:             "bz",
			SVGName:          "Belize",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "canada",
			Code:             "ca",
			SVGName:          "Canada",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "costa rica",
			Code:             "cr",
			SVGName:          "Costa Rica",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "cuba",
			Code:             "cu",
			SVGName:          "Cuba",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "dominica",
			Code:             "dm",
			SVGName:          "Dominica",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "dominican republic",
			Code:             "do",
			SVGName:          "Dominican Republic",
			AlternativeNames: []string{},
			Prefixes:         []string{"dominica"},
			Group:            "north america",
		},
		{
			Name:             "el salvador",
			Code:             "sv",
			SVGName:          "El Salvador",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "grenada",
			Code:             "gd",
			SVGName:          "Grenada",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "guatemala",
			Code:             "gt",
			SVGName:          "Guatemala",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "haiti",
			Code:             "ht",
			SVGName:          "Haiti",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "honduras",
			Code:             "hn",
			SVGName:          "Honduras",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "jamaica",
			Code:             "jm",
			SVGName:          "Jamaica",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "mexico",
			Code:             "mx",
			SVGName:          "Mexico",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "nicaragua",
			Code:             "ni",
			SVGName:          "Nicaragua",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "panama",
			Code:             "pa",
			SVGName:          "Panama",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "saint kitts and nevis",
			Code:             "kn",
			SVGName:          "Saint Kitts and Nevis",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "saint lucia",
			Code:             "lc",
			SVGName:          "Saint Lucia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "saint vincent and the grenadines",
			Code:             "vc",
			SVGName:          "Saint Vincent and the Grenadines",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "trinidad and tobago",
			Code:             "tt",
			SVGName:          "Trinidad and Tobago",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "united states",
			Code:             "us",
			SVGName:          "United States",
			AlternativeNames: []string{"usa"},
			Prefixes:         []string{},
			Group:            "north america",
		},
		{
			Name:             "argentina",
			Code:             "ar",
			SVGName:          "Argentina",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "bolivia",
			Code:             "bo",
			SVGName:          "Bolivia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "brazil",
			Code:             "br",
			SVGName:          "Brazil",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "chile",
			Code:             "cl",
			SVGName:          "Chile",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "colombia",
			Code:             "co",
			SVGName:          "Colombia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "ecuador",
			Code:             "ec",
			SVGName:          "Ecuador",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "guyana",
			Code:             "gy",
			SVGName:          "Guyana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "paraguay",
			Code:             "py",
			SVGName:          "Paraguay",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "peru",
			Code:             "pe",
			SVGName:          "Peru",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "suriname",
			Code:             "sr",
			SVGName:          "Suriname",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "uruguay",
			Code:             "uy",
			SVGName:          "Uruguay",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "venezuela",
			Code:             "ve",
			SVGName:          "Venezuela",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "south america",
		},
		{
			Name:             "australia",
			Code:             "au",
			SVGName:          "Australia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "federated states of micronesia",
			Code:             "fm",
			SVGName:          "Federated States of Micronesia",
			AlternativeNames: []string{"micronesia"},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "fiji",
			Code:             "fj",
			SVGName:          "Fiji",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "kiribati",
			Code:             "ki",
			SVGName:          "Kiribati",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "marshall islands",
			Code:             "mh",
			SVGName:          "Marshall Islands",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "nauru",
			Code:             "nr",
			SVGName:          "Nauru",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "new zealand",
			Code:             "nz",
			SVGName:          "New Zealand",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "palau",
			Code:             "pw",
			SVGName:          "Palau",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "papua new guinea",
			Code:             "pg",
			SVGName:          "Papua New Guinea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "samoa",
			Code:             "ws",
			SVGName:          "Samoa",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "solomon islands",
			Code:             "sb",
			SVGName:          "Solomon Islands",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "tonga",
			Code:             "to",
			SVGName:          "Tonga",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "tuvalu",
			Code:             "tv",
			SVGName:          "Tuvalu",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
		{
			Name:             "vanuatu",
			Code:             "vu",
			SVGName:          "Vanuatu",
			AlternativeNames: []string{},
			Prefixes:         []string{},
			Group:            "oceania",
		},
	},
	"uk": {
		{
			Name:             "bedfordshire",
			Code:             "gb-bd",
			SVGName:          "Bedfordshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "berkshire",
			Code:             "gb-bk",
			SVGName:          "Berkshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "bristol",
			Code:             "gb-bst",
			SVGName:          "Bristol",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "buckinghamshire",
			Code:             "gb-bu",
			SVGName:          "Buckinghamshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "cambridgeshire",
			Code:             "gb-cm",
			SVGName:          "Cambridgeshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "cheshire",
			Code:             "gb-ch",
			SVGName:          "Cheshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "cornwall",
			Code:             "gb-co",
			SVGName:          "Cornwall",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "cumbria",
			Code:             "gb-cu",
			SVGName:          "Cumbria",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "derbyshire",
			Code:             "gb-db",
			SVGName:          "Derbyshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "devon",
			Code:             "gb-dv",
			SVGName:          "Devon",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "dorset",
			Code:             "gb-ds",
			SVGName:          "Dorset",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "durham",
			Code:             "gb-dh",
			SVGName:          "Durham",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "essex",
			Code:             "gb-ex",
			SVGName:          "Essex",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "gloucestershire",
			Code:             "gb-gc",
			SVGName:          "Gloucestershire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "greater london",
			Code:             "gb-gl",
			SVGName:          "Greater London",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "hampshire",
			Code:             "gb-ha",
			SVGName:          "Hampshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "herefordshire",
			Code:             "gb-hd",
			SVGName:          "Herefordshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "hertfordshire",
			Code:             "gb-ht",
			SVGName:          "Hertfordshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "ireland",
			Code:             "ie",
			SVGName:          "Ireland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "kent",
			Code:             "gb-ke",
			SVGName:          "Kent",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "lancashire",
			Code:             "gb-la",
			SVGName:          "Lancashire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "leicestershire",
			Code:             "gb-le",
			SVGName:          "Leicestershire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "lincolnshire",
			Code:             "gb-li",
			SVGName:          "Lincolnshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "norfolk",
			Code:             "gb-nf",
			SVGName:          "Norfolk",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "northamptonshire",
			Code:             "gb-na",
			SVGName:          "Northamptonshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "northern ireland",
			Code:             "gb-ni",
			SVGName:          "Northern Ireland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "northumberland",
			Code:             "gb-nb",
			SVGName:          "Northumberland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "nottinghamshire",
			Code:             "gb-nt",
			SVGName:          "Nottinghamshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "oxfordshire",
			Code:             "gb-ox",
			SVGName:          "Oxfordshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "rutland",
			Code:             "gb-rt",
			SVGName:          "Rutland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "scotland",
			Code:             "gb-sc",
			SVGName:          "Scotland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "shropshire",
			Code:             "gb-sp",
			SVGName:          "Shropshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "somerset",
			Code:             "gb-sm",
			SVGName:          "Somerset",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "staffordshire",
			Code:             "gb-st",
			SVGName:          "Staffordshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "suffolk",
			Code:             "gb-sf",
			SVGName:          "Suffolk",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "surrey",
			Code:             "gb-sr",
			SVGName:          "Surrey",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "sussex",
			Code:             "gb-sx",
			SVGName:          "Sussex",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "wales",
			Code:             "gb-wa",
			SVGName:          "Wales",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "warwickshire",
			Code:             "gb-wr",
			SVGName:          "Warwickshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "wiltshire",
			Code:             "gb-wl",
			SVGName:          "Wiltshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "worcestershire",
			Code:             "gb-wo",
			SVGName:          "Worcestershire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "yorkshire",
			Code:             "gb-yk",
			SVGName:          "Yorkshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
	},
	"us": {
		{
			Name:             "alabama",
			Code:             "us-al",
			SVGName:          "Alabama",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "alaska",
			Code:             "us-ak",
			SVGName:          "Alaska",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "arizona",
			Code:             "us-az",
			SVGName:          "Arizona",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "arkansas",
			Code:             "us-ar",
			SVGName:          "Arkansas",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "california",
			Code:             "us-ca",
			SVGName:          "California",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "colorado",
			Code:             "us-co",
			SVGName:          "Colorado",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "connecticut",
			Code:             "us-ct",
			SVGName:          "Connecticut",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "delaware",
			Code:             "us-de",
			SVGName:          "Delaware",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "florida",
			Code:             "us-fl",
			SVGName:          "Florida",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "georgia",
			Code:             "us-ga",
			SVGName:          "Georgia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "hawaii",
			Code:             "us-hi",
			SVGName:          "Hawaii",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "idaho",
			Code:             "us-id",
			SVGName:          "Idaho",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "illinois",
			Code:             "us-il",
			SVGName:          "Illinois",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "indiana",
			Code:             "us-in",
			SVGName:          "Indiana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "iowa",
			Code:             "us-ia",
			SVGName:          "Iowa",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "kansas",
			Code:             "us-ks",
			SVGName:          "Kansas",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "kentucky",
			Code:             "us-ky",
			SVGName:          "Kentucky",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "louisiana",
			Code:             "us-la",
			SVGName:          "Louisiana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "maine",
			Code:             "us-me",
			SVGName:          "Maine",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "maryland",
			Code:             "us-md",
			SVGName:          "Maryland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "massachusetts",
			Code:             "us-ma",
			SVGName:          "Massachusetts",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "michigan",
			Code:             "us-mi",
			SVGName:          "Michigan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "minnesota",
			Code:             "us-mn",
			SVGName:          "Minnesota",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "mississippi",
			Code:             "us-ms",
			SVGName:          "Mississippi",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "missouri",
			Code:             "us-mo",
			SVGName:          "Missouri",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "montana",
			Code:             "us-mt",
			SVGName:          "Montana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "nebraska",
			Code:             "us-ne",
			SVGName:          "Nebraska",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "nevada",
			Code:             "us-nv",
			SVGName:          "Nevada",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "new hampshire",
			Code:             "us-nh",
			SVGName:          "New Hampshire",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "new jersey",
			Code:             "us-nj",
			SVGName:          "New Jersey",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "new mexico",
			Code:             "us-nm",
			SVGName:          "New Mexico",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "new york",
			Code:             "us-ny",
			SVGName:          "New York",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "north carolina",
			Code:             "us-nc",
			SVGName:          "North Carolina",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "north dakota",
			Code:             "us-nd",
			SVGName:          "North Dakota",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "ohio",
			Code:             "us-oh",
			SVGName:          "Ohio",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "oklahoma",
			Code:             "us-ok",
			SVGName:          "Oklahoma",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "oregon",
			Code:             "us-or",
			SVGName:          "Oregon",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "pennsylvania",
			Code:             "us-pa",
			SVGName:          "Pennsylvania",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "rhode island",
			Code:             "us-ri",
			SVGName:          "Rhode Island",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "south carolina",
			Code:             "us-sc",
			SVGName:          "South Carolina",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "south dakota",
			Code:             "us-sd",
			SVGName:          "South Dakota",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "tennessee",
			Code:             "us-tn",
			SVGName:          "Tennessee",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "texas",
			Code:             "us-tx",
			SVGName:          "Texas",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "utah",
			Code:             "us-ut",
			SVGName:          "Utah",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "vermont",
			Code:             "us-vt",
			SVGName:          "Vermont",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "virginia",
			Code:             "us-va",
			SVGName:          "Virginia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "washington",
			Code:             "us-wa",
			SVGName:          "Washington",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "washington, dc",
			Code:             "us-dc",
			SVGName:          "Washington, DC",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "west virginia",
			Code:             "us-wv",
			SVGName:          "West Virginia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "wisconsin",
			Code:             "us-wi",
			SVGName:          "Wisconsin",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "wyoming",
			Code:             "us-wy",
			SVGName:          "Wyoming",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
	},
}
