package mapping

// UKCounties is a list of UK county mappings.
var UKCounties = []Mapping{
	{
		Name:             "bedfordshire",
		Code:             "gb-bd",
		SVGName:          "Bedfordshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "berkshire",
		Code:             "gb-bk",
		SVGName:          "Berkshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "bristol",
		Code:             "gb-bst",
		SVGName:          "Bristol",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "buckinghamshire",
		Code:             "gb-bu",
		SVGName:          "Buckinghamshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "cambridgeshire",
		Code:             "gb-cm",
		SVGName:          "Cambridgeshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "cheshire",
		Code:             "gb-ch",
		SVGName:          "Cheshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "cornwall",
		Code:             "gb-co",
		SVGName:          "Cornwall",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "cumbria",
		Code:             "gb-cu",
		SVGName:          "Cumbria",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "derbyshire",
		Code:             "gb-db",
		SVGName:          "Derbyshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "devon",
		Code:             "gb-dv",
		SVGName:          "Devon",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "dorset",
		Code:             "gb-ds",
		SVGName:          "Dorset",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "durham",
		Code:             "gb-dh",
		SVGName:          "Durham",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "essex",
		Code:             "gb-ex",
		SVGName:          "Essex",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "gloucestershire",
		Code:             "gb-gc",
		SVGName:          "Gloucestershire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "greater london",
		Code:             "gb-gl",
		SVGName:          "Greater London",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "hampshire",
		Code:             "gb-ha",
		SVGName:          "Hampshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "herefordshire",
		Code:             "gb-hd",
		SVGName:          "Herefordshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "hertfordshire",
		Code:             "gb-ht",
		SVGName:          "Hertfordshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "ireland",
		Code:             "ie",
		SVGName:          "Ireland",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "kent",
		Code:             "gb-ke",
		SVGName:          "Kent",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "lancashire",
		Code:             "gb-la",
		SVGName:          "Lancashire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "leicestershire",
		Code:             "gb-le",
		SVGName:          "Leicestershire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "lincolnshire",
		Code:             "gb-li",
		SVGName:          "Lincolnshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "norfolk",
		Code:             "gb-nf",
		SVGName:          "Norfolk",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "northamptonshire",
		Code:             "gb-na",
		SVGName:          "Northamptonshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "northern ireland",
		Code:             "gb-ni",
		SVGName:          "Northern Ireland",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "northumberland",
		Code:             "gb-nb",
		SVGName:          "Northumberland",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "nottinghamshire",
		Code:             "gb-nt",
		SVGName:          "Nottinghamshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "oxfordshire",
		Code:             "gb-ox",
		SVGName:          "Oxfordshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "rutland",
		Code:             "gb-rt",
		SVGName:          "Rutland",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "scotland",
		Code:             "gb-sc",
		SVGName:          "Scotland",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "shropshire",
		Code:             "gb-sp",
		SVGName:          "Shropshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "somerset",
		Code:             "gb-sm",
		SVGName:          "Somerset",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "staffordshire",
		Code:             "gb-st",
		SVGName:          "Staffordshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "suffolk",
		Code:             "gb-sf",
		SVGName:          "Suffolk",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "surrey",
		Code:             "gb-sr",
		SVGName:          "Surrey",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "sussex",
		Code:             "gb-sx",
		SVGName:          "Sussex",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "wales",
		Code:             "gb-wa",
		SVGName:          "Wales",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "warwickshire",
		Code:             "gb-wr",
		SVGName:          "Warwickshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "wiltshire",
		Code:             "gb-wl",
		SVGName:          "Wiltshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "worcestershire",
		Code:             "gb-wo",
		SVGName:          "Worcestershire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "yorkshire",
		Code:             "gb-yk",
		SVGName:          "Yorkshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
}
