package mapping

// USStates is a list of US state mappings.
var USStates = []Mapping{
	{
		Name:             "alabama",
		Code:             "us-al",
		SVGName:          "Alabama",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "alaska",
		Code:             "us-ak",
		SVGName:          "Alaska",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "arizona",
		Code:             "us-az",
		SVGName:          "Arizona",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "arkansas",
		Code:             "us-ar",
		SVGName:          "Arkansas",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "california",
		Code:             "us-ca",
		SVGName:          "California",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "colorado",
		Code:             "us-co",
		SVGName:          "Colorado",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "connecticut",
		Code:             "us-ct",
		SVGName:          "Connecticut",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "delaware",
		Code:             "us-de",
		SVGName:          "Delaware",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "florida",
		Code:             "us-fl",
		SVGName:          "Florida",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "georgia",
		Code:             "us-ga",
		SVGName:          "Georgia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "hawaii",
		Code:             "us-hi",
		SVGName:          "Hawaii",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "idaho",
		Code:             "us-id",
		SVGName:          "Idaho",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "illinois",
		Code:             "us-il",
		SVGName:          "Illinois",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "indiana",
		Code:             "us-in",
		SVGName:          "Indiana",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "iowa",
		Code:             "us-ia",
		SVGName:          "Iowa",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "kansas",
		Code:             "us-ks",
		SVGName:          "Kansas",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "kentucky",
		Code:             "us-ky",
		SVGName:          "Kentucky",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "louisiana",
		Code:             "us-la",
		SVGName:          "Louisiana",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "maine",
		Code:             "us-me",
		SVGName:          "Maine",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "maryland",
		Code:             "us-md",
		SVGName:          "Maryland",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "massachusetts",
		Code:             "us-ma",
		SVGName:          "Massachusetts",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "michigan",
		Code:             "us-mi",
		SVGName:          "Michigan",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "minnesota",
		Code:             "us-mn",
		SVGName:          "Minnesota",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "mississippi",
		Code:             "us-ms",
		SVGName:          "Mississippi",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "missouri",
		Code:             "us-mo",
		SVGName:          "Missouri",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "montana",
		Code:             "us-mt",
		SVGName:          "Montana",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "nebraska",
		Code:             "us-ne",
		SVGName:          "Nebraska",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "nevada",
		Code:             "us-nv",
		SVGName:          "Nevada",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "new hampshire",
		Code:             "us-nh",
		SVGName:          "New Hampshire",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "new jersey",
		Code:             "us-nj",
		SVGName:          "New Jersey",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "new mexico",
		Code:             "us-nm",
		SVGName:          "New Mexico",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "new york",
		Code:             "us-ny",
		SVGName:          "New York",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "north carolina",
		Code:             "us-nc",
		SVGName:          "North Carolina",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "north dakota",
		Code:             "us-nd",
		SVGName:          "North Dakota",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "ohio",
		Code:             "us-oh",
		SVGName:          "Ohio",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "oklahoma",
		Code:             "us-ok",
		SVGName:          "Oklahoma",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "oregon",
		Code:             "us-or",
		SVGName:          "Oregon",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "pennsylvania",
		Code:             "us-pa",
		SVGName:          "Pennsylvania",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "rhode island",
		Code:             "us-ri",
		SVGName:          "Rhode Island",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "south carolina",
		Code:             "us-sc",
		SVGName:          "South Carolina",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "south dakota",
		Code:             "us-sd",
		SVGName:          "South Dakota",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "tennessee",
		Code:             "us-tn",
		SVGName:          "Tennessee",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "texas",
		Code:             "us-tx",
		SVGName:          "Texas",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "utah",
		Code:             "us-ut",
		SVGName:          "Utah",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "vermont",
		Code:             "us-vt",
		SVGName:          "Vermont",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "virginia",
		Code:             "us-va",
		SVGName:          "Virginia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "washington",
		Code:             "us-wa",
		SVGName:          "Washington",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "washington, dc",
		Code:             "us-dc",
		SVGName:          "Washington, DC",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "west virginia",
		Code:             "us-wv",
		SVGName:          "West Virginia",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "wisconsin",
		Code:             "us-wi",
		SVGName:          "Wisconsin",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
	{
		Name:             "wyoming",
		Code:             "us-wy",
		SVGName:          "Wyoming",
		AlternativeNames: []string{},
		Prefixes:         []string{},
	},
}
