package main

// Country represents a countries mapping data.
type Country struct {
	Name             string   `json:"name"`
	Code             string   `json:"code"`
	SVGName          string   `json:"svgName"`
	AlternativeNames []string `json:"alternativeNames"`
	Prefixes         []string `json:"prefixes"`
}

// Countries is a map of countries by continent.
var Countries = map[string][]Country{
	"africa": {
		{
			Name:             "egypt",
			Code:             "eg",
			SVGName:          "Egypt",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "algeria",
			Code:             "dz",
			SVGName:          "Algeria",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "angola",
			Code:             "ao",
			SVGName:          "Angola",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "benin",
			Code:             "bj",
			SVGName:          "Benin",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "botswana",
			Code:             "bw",
			SVGName:          "Botswana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "burkina faso",
			Code:             "bf",
			SVGName:          "Burkina Faso",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "burundi",
			Code:             "bi",
			SVGName:          "Burundi",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "cameroon",
			Code:             "cm",
			SVGName:          "Cameroon",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "cape verde",
			Code:             "cv",
			SVGName:          "Cape Verde",
			AlternativeNames: []string{"cabo verde"},
			Prefixes:         []string{},
		},
		{
			Name:             "central african republic",
			Code:             "cf",
			SVGName:          "Central African Republic",
			AlternativeNames: []string{"car"},
			Prefixes:         []string{},
		},
		{
			Name:             "chad",
			Code:             "td",
			SVGName:          "Chad",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "comoros",
			Code:             "km",
			SVGName:          "Comoros",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "republic of congo",
			Code:             "cg",
			SVGName:          "Republic of Congo",
			AlternativeNames: []string{"republic of the congo", "congo, republic of the"},
			Prefixes:         []string{},
		},
		{
			Name:             "democratic republic of congo",
			Code:             "cd",
			SVGName:          "Democratic Republic of Congo",
			AlternativeNames: []string{"congo, democratic republic of the", "drc"},
			Prefixes:         []string{},
		},
		{
			Name:             "cote d'ivoire",
			Code:             "ci",
			SVGName:          "Côte d'Ivoire",
			AlternativeNames: []string{"côte d'ivoire", "ivory coast"},
			Prefixes:         []string{},
		},
		{
			Name:             "djibouti",
			Code:             "dj",
			SVGName:          "Djibouti",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "equatorial guinea",
			Code:             "gq",
			SVGName:          "Equatorial Guinea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "eritrea",
			Code:             "er",
			SVGName:          "Eritrea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "ethiopia",
			Code:             "et",
			SVGName:          "Ethiopia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "gabon",
			Code:             "ga",
			SVGName:          "Gabon",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "gambia",
			Code:             "gm",
			SVGName:          "Gambia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "ghana",
			Code:             "gh",
			SVGName:          "Ghana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "guinea",
			Code:             "gn",
			SVGName:          "Guinea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		}, {
			Name:             "guinea-bissau",
			Code:             "gw",
			SVGName:          "Guinea-Bissau",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "kenya",
			Code:             "ke",
			SVGName:          "Kenya",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "lesotho",
			Code:             "ls",
			SVGName:          "Lesotho",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "liberia",
			Code:             "lr",
			SVGName:          "Liberia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "libya",
			Code:             "ly",
			SVGName:          "Libya",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "madagascar",
			Code:             "mg",
			SVGName:          "Madagascar",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "malawi",
			Code:             "mw",
			SVGName:          "Malawi",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "mali",
			Code:             "ml",
			SVGName:          "Mali",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "mauritania",
			Code:             "mr",
			SVGName:          "Mauritania",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "mauritius",
			Code:             "mu",
			SVGName:          "Mauritius",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "morocco",
			Code:             "ma",
			SVGName:          "Morocco",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "mozambique",
			Code:             "mz",
			SVGName:          "Mozambique",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "namibia",
			Code:             "na",
			SVGName:          "Namibia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "niger",
			Code:             "ne",
			SVGName:          "Niger",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "nigeria",
			Code:             "ng",
			SVGName:          "Nigeria",
			AlternativeNames: []string{},
			Prefixes:         []string{"niger"},
		},
		{
			Name:             "rwanda",
			Code:             "rw",
			SVGName:          "Rwanda",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "sao tome and principe",
			Code:             "st",
			SVGName:          "Sao Tome and Principe",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "senegal",
			Code:             "sn",
			SVGName:          "Senegal",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "seychelles",
			Code:             "sc",
			SVGName:          "Seychelles",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "sierra leone",
			Code:             "sl",
			SVGName:          "Sierra Leone",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "somalia",
			Code:             "so",
			SVGName:          "Somalia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "south africa",
			Code:             "za",
			SVGName:          "South Africa",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "south sudan",
			Code:             "ss",
			SVGName:          "South Sudan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "swaziland",
			Code:             "sz",
			SVGName:          "Swaziland",
			AlternativeNames: []string{"eswatini"},
			Prefixes:         []string{},
		},
		{
			Name:             "tanzania",
			Code:             "tz",
			SVGName:          "Tanzania",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "togo",
			Code:             "tg",
			SVGName:          "Togo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "tunisia",
			Code:             "tn",
			SVGName:          "Tunisia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "uganda",
			Code:             "ug",
			SVGName:          "Uganda",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "zambia",
			Code:             "zm",
			SVGName:          "Zambia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "sudan",
			Code:             "sd",
			SVGName:          "Sudan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "zimbabwe",
			Code:             "zw",
			SVGName:          "Zimbabwe",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
	},
	"antarctica": {},
	"asia": {
		{
			Name:             "afghanistan",
			Code:             "af",
			SVGName:          "Afghanistan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "armenia",
			Code:             "am",
			SVGName:          "Armenia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "azerbaijan",
			Code:             "az",
			SVGName:          "Azerbaijan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "bahrain",
			Code:             "bh",
			SVGName:          "Bahrain",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "bangladesh",
			Code:             "bd",
			SVGName:          "Bangladesh",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "bhutan",
			Code:             "bt",
			SVGName:          "Bhutan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "brunei",
			Code:             "bn",
			SVGName:          "Brunei Darussalam",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "cambodia",
			Code:             "kh",
			SVGName:          "Cambodia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "china",
			Code:             "cn",
			SVGName:          "China",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "timor-leste",
			Code:             "tl",
			SVGName:          "Timor-Leste",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "georgia",
			Code:             "ge",
			SVGName:          "Georgia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "india",
			Code:             "in",
			SVGName:          "India",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		}, {
			Name:             "indonesia",
			Code:             "id",
			SVGName:          "Indonesia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "iran",
			Code:             "ir",
			SVGName:          "Iran",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		}, {
			Name:             "iraq",
			Code:             "iq",
			SVGName:          "Iraq",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "israel",
			Code:             "il",
			SVGName:          "Israel",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "japan",
			Code:             "jp",
			SVGName:          "Japan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "jordan",
			Code:             "jo",
			SVGName:          "Jordan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		}, {
			Name:             "kazakhstan",
			Code:             "kz",
			SVGName:          "Kazakhstan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "kuwait",
			Code:             "kw",
			SVGName:          "Kuwait",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		}, {
			Name:             "kyrgyzstan",
			Code:             "kg",
			SVGName:          "Kyrgyzstan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		}, {
			Name:             "lao people's democratic republic",
			Code:             "la",
			SVGName:          "Lao People's Democratic Republic",
			AlternativeNames: []string{"laos"},
			Prefixes:         []string{},
		},
		{
			Name:             "lebanon",
			Code:             "lb",
			SVGName:          "Lebanon",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "malaysia",
			Code:             "my",
			SVGName:          "Malaysia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		}, {
			Name:             "maldives",
			Code:             "mv",
			SVGName:          "Maldives",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "mongolia",
			Code:             "mn",
			SVGName:          "Mongolia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "myanmar",
			Code:             "mm",
			SVGName:          "Myanmar",
			AlternativeNames: []string{"burma"},
			Prefixes:         []string{},
		},
		{
			Name:             "nepal",
			Code:             "np",
			SVGName:          "Nepal",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "north korea",
			Code:             "kp",
			SVGName:          "North Korea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "oman",
			Code:             "om",
			SVGName:          "Oman",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "pakistan",
			Code:             "pk",
			SVGName:          "Pakistan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "philippines",
			Code:             "ph",
			SVGName:          "Philippines",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "qatar",
			Code:             "qa",
			SVGName:          "Qatar",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "russia",
			Code:             "ru",
			SVGName:          "Russia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "saudi arabia",
			Code:             "sa",
			SVGName:          "Saudi Arabia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "singapore",
			Code:             "sg",
			SVGName:          "Singapore",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "south korea",
			Code:             "kr",
			SVGName:          "South Korea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "sri lanka",
			Code:             "lk",
			SVGName:          "Sri Lanka",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "syria",
			Code:             "sy",
			SVGName:          "Syria",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "tajikistan",
			Code:             "tj",
			SVGName:          "Tajikistan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "thailand",
			Code:             "th",
			SVGName:          "Thailand",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "turkey",
			Code:             "tr",
			SVGName:          "Turkey",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "turkmenistan",
			Code:             "tm",
			SVGName:          "Turkmenistan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "taiwan",
			Code:             "tw",
			SVGName:          "Taiwan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "united arab emirates",
			Code:             "ae",
			SVGName:          "United Arab Emirates",
			AlternativeNames: []string{"uae"},
			Prefixes:         []string{},
		},
		{
			Name:             "uzbekistan",
			Code:             "uz",
			SVGName:          "Uzbekistan",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "vietnam",
			Code:             "vn",
			SVGName:          "Vietnam",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "yemen",
			Code:             "ye",
			SVGName:          "Yemen",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
	},
	"europe": {
		{
			Name:             "albania",
			Code:             "al",
			SVGName:          "Albania",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "andorra",
			Code:             "ad",
			SVGName:          "Andorra",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "austria",
			Code:             "at",
			SVGName:          "Austria",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "belarus",
			Code:             "by",
			SVGName:          "Belarus",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "belgium",
			Code:             "be",
			SVGName:          "Belgium",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "bosnia and herzegovina",
			Code:             "ba",
			SVGName:          "Bosnia and Herzegovina",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "bulgaria",
			Code:             "bg",
			SVGName:          "Bulgaria",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "croatia",
			Code:             "hr",
			SVGName:          "Croatia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "cyprus",
			Code:             "cy",
			SVGName:          "Cyprus",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "czech republic",
			Code:             "cz",
			SVGName:          "Czech Republic",
			AlternativeNames: []string{"czechia"},
			Prefixes:         []string{},
		},
		{
			Name:             "denmark",
			Code:             "dk",
			SVGName:          "Denmark",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "estonia",
			Code:             "ee",
			SVGName:          "Estonia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "finland",
			Code:             "fi",
			SVGName:          "Finland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "france",
			Code:             "fr",
			SVGName:          "France",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "germany",
			Code:             "de",
			SVGName:          "Germany",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "greece",
			Code:             "gr",
			SVGName:          "Greece",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "hungary",
			Code:             "hu",
			SVGName:          "Hungary",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "iceland",
			Code:             "is",
			SVGName:          "Iceland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "ireland",
			Code:             "ie",
			SVGName:          "Ireland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "italy",
			Code:             "it",
			SVGName:          "Italy",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "kosovo",
			Code:             "xk",
			SVGName:          "Kosovo",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "latvia",
			Code:             "lv",
			SVGName:          "Latvia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "liechtenstein",
			Code:             "li",
			SVGName:          "Liechtenstein",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "lithuania",
			Code:             "lt",
			SVGName:          "Lithuania",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "luxembourg",
			Code:             "lu",
			SVGName:          "Luxembourg",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "macedonia",
			Code:             "mk",
			SVGName:          "Macedonia",
			AlternativeNames: []string{"north macedonia"},
			Prefixes:         []string{},
		},
		{
			Name:             "malta",
			Code:             "mt",
			SVGName:          "Malta",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "moldova",
			Code:             "md",
			SVGName:          "Moldova",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "monaco",
			Code:             "mc",
			SVGName:          "Monaco",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "montenegro",
			Code:             "me",
			SVGName:          "Montenegro",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "netherlands",
			Code:             "nl",
			SVGName:          "Netherlands",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "norway",
			Code:             "no",
			SVGName:          "Norway",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "palestinian territories",
			Code:             "ps",
			SVGName:          "Palestinian Territories",
			AlternativeNames: []string{"palestine"},
			Prefixes:         []string{},
		},
		{
			Name:             "poland",
			Code:             "pl",
			SVGName:          "Poland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "portugal",
			Code:             "pt",
			SVGName:          "Portugal",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "romania",
			Code:             "ro",
			SVGName:          "Romania",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "san marino",
			Code:             "sm",
			SVGName:          "San Marino",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "serbia",
			Code:             "rs",
			SVGName:          "Serbia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "slovakia",
			Code:             "sk",
			SVGName:          "Slovakia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "slovenia",
			Code:             "si",
			SVGName:          "Slovenia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "spain",
			Code:             "es",
			SVGName:          "Spain",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "sweden",
			Code:             "se",
			SVGName:          "Sweden",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "switzerland",
			Code:             "ch",
			SVGName:          "Switzerland",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "ukraine",
			Code:             "ua",
			SVGName:          "Ukraine",
			AlternativeNames: []string{},
			Prefixes:         []string{"uk"},
		},
		{
			Name:             "united kingdom",
			Code:             "gb",
			SVGName:          "United Kingdom",
			AlternativeNames: []string{"uk"},
			Prefixes:         []string{},
		},
		{
			Name:             "vatican city",
			Code:             "va",
			SVGName:          "Vatican City",
			AlternativeNames: []string{"holy see"},
			Prefixes:         []string{},
		},
	},
	"north america": {
		{
			Name:             "canada",
			Code:             "ca",
			SVGName:          "Canada",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "united states",
			Code:             "us",
			SVGName:          "United States",
			AlternativeNames: []string{"usa"},
			Prefixes:         []string{},
		},
		{
			Name:             "mexico",
			Code:             "mx",
			SVGName:          "Mexico",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "belize",
			Code:             "bz",
			SVGName:          "Belize",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "antigua and barbuda",
			Code:             "ag",
			SVGName:          "Antigua and Barbuda",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "bahamas",
			Code:             "bs",
			SVGName:          "Bahamas",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "barbados",
			Code:             "bb",
			SVGName:          "Barbados",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "costa rica",
			Code:             "cr",
			SVGName:          "Costa Rica",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "cuba",
			Code:             "cu",
			SVGName:          "Cuba",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "dominica",
			Code:             "dm",
			SVGName:          "Dominica",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "dominican republic",
			Code:             "do",
			SVGName:          "Dominican Republic",
			AlternativeNames: []string{},
			Prefixes:         []string{"dominica"},
		},
		{
			Name:             "el salvador",
			Code:             "sv",
			SVGName:          "El Salvador",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "grenada",
			Code:             "gd",
			SVGName:          "Grenada",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "guatemala",
			Code:             "gt",
			SVGName:          "Guatemala",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "haiti",
			Code:             "ht",
			SVGName:          "Haiti",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "honduras",
			Code:             "hn",
			SVGName:          "Honduras",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "jamaica",
			Code:             "jm",
			SVGName:          "Jamaica",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "nicaragua",
			Code:             "ni",
			SVGName:          "Nicaragua",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "panama",
			Code:             "pa",
			SVGName:          "Panama",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "saint kitts and nevis",
			Code:             "kn",
			SVGName:          "Saint Kitts and Nevis",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "saint lucia",
			Code:             "lc",
			SVGName:          "Saint Lucia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "saint vincent and the grenadines",
			Code:             "vc",
			SVGName:          "Saint Vincent and the Grenadines",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "trinidad and tobago",
			Code:             "tt",
			SVGName:          "Trinidad and Tobago",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
	},
	"south america": {
		{
			Name:             "brazil",
			Code:             "br",
			SVGName:          "Brazil",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "argentina",
			Code:             "ar",
			SVGName:          "Argentina",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "bolivia",
			Code:             "bo",
			SVGName:          "Bolivia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "chile",
			Code:             "cl",
			SVGName:          "Chile",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "colombia",
			Code:             "co",
			SVGName:          "Colombia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "ecuador",
			Code:             "ec",
			SVGName:          "Ecuador",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "guyana",
			Code:             "gy",
			SVGName:          "Guyana",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "paraguay",
			Code:             "py",
			SVGName:          "Paraguay",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "peru",
			Code:             "pe",
			SVGName:          "Peru",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "suriname",
			Code:             "sr",
			SVGName:          "Suriname",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "uruguay",
			Code:             "uy",
			SVGName:          "Uruguay",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "venezuela",
			Code:             "ve",
			SVGName:          "Venezuela",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
	},
	"oceania": {
		{
			Name:             "australia",
			Code:             "au",
			SVGName:          "Australia",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "fiji",
			Code:             "fj",
			SVGName:          "Fiji",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "new zealand",
			Code:             "nz",
			SVGName:          "New Zealand",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "federated states of micronesia",
			Code:             "fm",
			SVGName:          "Federated States of Micronesia",
			AlternativeNames: []string{"micronesia"},
			Prefixes:         []string{},
		},
		{
			Name:             "kiribati",
			Code:             "ki",
			SVGName:          "Kiribati",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "marshall islands",
			Code:             "mh",
			SVGName:          "Marshall Islands",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "nauru",
			Code:             "nr",
			SVGName:          "Nauru",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "palau",
			Code:             "pw",
			SVGName:          "Palau",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "papua new guinea",
			Code:             "pg",
			SVGName:          "Papua New Guinea",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "samoa",
			Code:             "ws",
			SVGName:          "Samoa",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "solomon islands",
			Code:             "sb",
			SVGName:          "Solomon Islands",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "tonga",
			Code:             "to",
			SVGName:          "Tonga",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "tuvalu",
			Code:             "tv",
			SVGName:          "Tuvalu",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
		{
			Name:             "vanuatu",
			Code:             "vu",
			SVGName:          "Vanuatu",
			AlternativeNames: []string{},
			Prefixes:         []string{},
		},
	},
}
